language: r
cache: packages

r:
  - oldrel
  - release
  - devel

env:
  global:
    - IMONGR_DB_HOST="127.0.0.1"
    - IMONGR_DB_NAME="testdb"
    - IMONGR_DB_USER="travis"
    - IMONGR_DB_PASS=""

services:
  - mysql

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - r-lib/pkgdown

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS testdb CHARACTER SET = 'utf8' COLLATE = 'utf8_danish_ci';"


after_success:
  - R CMD INSTALL $PKG_TARBALL
  - |
    if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
      Rscript -e 'covr::codecov()'
    fi
  - rm -rf imongr.Rcheck
  - Rscript -e 'pkgdown::build_site()'

deploy:
  # our site to gh_pages
  - provider: pages
    skip_cleanup: true
    keep_history: false
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
