language: r
cache: packages
os: linux
dist: xenial

warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

env:
  global:
    - IMONGR_DB_HOST="127.0.0.1"
    - IMONGR_DB_NAME="testdb"
    - IMONGR_DB_USER="travis"
    - IMONGR_DB_PASS=""
    - _R_CHECK_TESTS_NLINES_=0

services:
  - mysql
  - docker

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - r-lib/pkgdown
  - rstudio/shiny

before_install:
  - sudo apt-get -y install libharfbuzz-dev libfribidi-dev
  - mysql -e "CREATE DATABASE IF NOT EXISTS testdb CHARACTER SET = 'utf8' COLLATE = 'utf8_danish_ci';"
  - R CMD build .
  - docker build -t $DOCKER_ORG/$IMAGE_NAME .
  - rm imongr_*.tar.gz
  - docker run -d -p 127.0.0.1:3838:3838 -e SHINYPROXY_USERNAME='ci' --name $IMAGE_NAME $DOCKER_ORG/$IMAGE_NAME

before_script:
  - docker ps | grep -q $IMAGE_NAME
  - curl -IsSf 127.0.0.1:3838 > /dev/null

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - |
    if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
      Rscript -e 'covr::codecov()'
    fi
  - rm -rf imongr.Rcheck
  - Rscript -e 'pkgdown::build_site()'

deploy:
  # our site to gh_pages
  - provider: pages
    skip_cleanup: true
    token: $GH_TOKEN
    keep_history: false
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
