proxy:
  title: imongr
  hide-navbar: true
  landing-page: /
  port: 8080
  container-wait-time: 20000
  authentication: openid
  openid:
    auth-url: https://dev-4bsfd97d.eu.auth0.com/authorize
    token-url: https://dev-4bsfd97d.eu.auth0.com/oauth/token
    jwks-url: https://dev-4bsfd97d.eu.auth0.com/.well-known/jwks.json
    client_id: ${OPENID_CLIENT_ID}
    client_secret: ${OPENID_CLIENT_SECRET}
    roles-claim: https://mongr.no/imongr/shinyproxy_roles
  docker:
    internal-networking: true
  usage-stats-url: http://172.31.31.109:8086/write?db=shinyproxy_usagestats
  specs:
  - id: imongr
    display-name: imongr
    container-cmd: ["R", "-e", "options(shiny.port=3838,shiny.host='0.0.0.0'); imongr::run_app()"]
    container-image: hnskde/imongr
    container-network: mongr-net
    container-env:
      IMONGR_DB_HOST: ${IMONGR_DB_HOST}
      IMONGR_DB_NAME: ${IMONGR_DB_NAME}
      IMONGR_DB_USER: ${IMONGR_DB_USER}
      IMONGR_DB_PASS: ${IMONGR_DB_PASS}
