version: '3.6'

services:

  db:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imongr
      MYSQL_USER: imongr
      MYSQL_PASSWORD: imongr
    volumes:
      - ./inst:/docker-entrypoint-initdb.d
    ports:
      - 3331:3306

  db-verify:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imongr
      MYSQL_USER: imongr
      MYSQL_PASSWORD: imongr
    volumes:
      - ./inst:/docker-entrypoint-initdb.d
    ports:
      - 3332:3306

  db-qa:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imongr
      MYSQL_USER: imongr
      MYSQL_PASSWORD: imongr
    volumes:
      - ./inst:/docker-entrypoint-initdb.d
    ports:
      - 3333:3306


  dev:
    depends_on:
      - db
    image: hnskde/mongr-dev:latest
    platform: linux/x86_64
    restart: "no"
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - .:/home/rstudio/imongr
    ports:
      - 8787:8787
    environment:
      PASSWORD: password

  app:
    image: hnskde/imongr:latest
    platform: linux/x86_64
    ports:
      - 3838:3838
    environment:
      IMONGR_DB_HOST: db
      IMONGR_DB_HOST_VERIFY: db-verify
      IMONGR_DB_HOST_QA: db-qa
      IMONGR_DB_NAME: imongr
      IMONGR_DB_USER: imongr
      IMONGR_DB_PASS: imongr
      IMONGR_ADMINER_URL: http://localhost:8888
      SHINYPROXY_USERNAME: imongr@mongr.no
      SHINYPROXY_USERGROUPS: PROVIDER,MANAGER

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080

