version: '3.6'

services:

  db:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imongr
      MYSQL_USER: imongr
      MYSQL_PASSWORD: imongr
    volumes:
      - ./inst:/docker-entrypoint-initdb.d

  db-verify:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imongr
      MYSQL_USER: imongr
      MYSQL_PASSWORD: imongr
    volumes:
      - ./inst:/docker-entrypoint-initdb.d

  db-qa:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imongr
      MYSQL_USER: imongr
      MYSQL_PASSWORD: imongr
    volumes:
      - ./inst:/docker-entrypoint-initdb.d


  dev:
    depends_on:
      - db
    image: hnskde/mongr-dev
    restart: "no"
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
    ports:
      - 8787:8787
    environment:
      PASSWORD: password

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080

