on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test-coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: ubuntu-24.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTIONS_RUN_DB_UNIT_TESTS: true
      IMONGR_DB_HOST: "localhost"
      IMONGR_DB_NAME: "testdb"
      IMONGR_DB_USER: "root"
      IMONGR_DB_PASS: "root"
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage
  
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;' -uroot -proot

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
