name: Build and Deploy
on:
  push:
    branches:
      - fix_ghpages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install system dependencies
        run: sudo apt-get install libharfbuzz-dev libfribidi-dev libcurl4-openssl-dev
      - name: Install and Build 🔧
        run: |
          Rscript -e 'install.packages(c("roxygen2", "pkgdown"))'
          Rscript -e 'roxygen2::roxygenise()'
          Rscript -e 'pkgdown::build_site()'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
